comment:
  layout: "header, diff, changes, sunburst"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  branches: null
  flags: null
  paths: null
coverage:
  range: 70..100
  round: down
  precision: 2
ignore:
  - src/StateServiceProvider.php
  - src/StoreFacade.php