suites:
    acme_suite:
        namespace: Fetzi\State
        psr4_prefix: Fetzi\state
extensions:
  PhpSpecCodeCoverage\CodeCoverageExtension:
    format:
      - html
      - clover
    output:
      html: coverage
      clover: coverage.xml